server:
  port: 8090

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: bK5OTiQbOWo6Kc65WZLe4315noM4OjHN0xFpgwOYPbwknahqKztPSYQIqygumfIons42zpjnyE01GRsekvH6eS
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/microservices
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/microservices

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost