server:
  port: 8090

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${keycloak.issuer-uri}
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}

keycloak:
  issuer-uri: http://localhost:8180/realms/microservices

services:
  flow-manager:
    name: flow-manager
    path: /api/files
    route-id: flow-manager-route
  subscription-service:
    name: subscription-service
    path: /api/subscriptions
    route-id: subscription-service-route

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost